apiVersion: v2
name: maiakubegate
description: A Helm chart to deploy environments (pods, services, ingresses) and run experiments and applications in MAIA cluster

type: application

version: 1.0.0

appVersion: "1.0.0"
