maia-kube: 1.0
maia-dashboard: 1.3
maia-workspace: 1.0
maia-workspace-notebook: 1.1
maia-workspace-notebook-ssh: 1.0
maia-workspace-notebook-ssh-addons: 1.0
monai-toolkit: 1.0
maia-xnat: 1.0
monai-label-ohif-maia: 1.0